name: Build & Publish

on:
  schedule:
    - cron: '23 2 * * *'  # quotidien
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate pages
        run: |
          python -m pip install --upgrade pip
          python scripts/generate.py
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "build: update pages" || echo "No changes"
          git push
