name: Build & Publish

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '23 2 * * *'   # quotidien

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITE_ROOT: "https://guide-facile.fr"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # Toujours se resynchroniser avec la branche distante avant de générer
      - name: Sync with remote main
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate static pages
        run: |
          python -m pip install --upgrade pip
          python scripts/generate.py
          echo "Generation finished."

      - name: Commit & Push generated pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "build: update pages (SITE_ROOT)" || echo "No changes"
          git push origin HEAD:main
