name: Build & Publish

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '23 2 * * *'   # quotidien

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITE_ROOT: "https://guide-facile.fr"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate static pages
        run: |
          python -m pip install --upgrade pip
          python scripts/generate.py
          echo "Generation finished."

      - name: Commit generated pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update pages (SITE_ROOT)"
